[package]
name = "libjose"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A library for JOSE (JSON Object Signing and Encryption)"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "jose", "jwa", "jwe", "jwk", "jws", "jwt"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
