[package]
name = "libjose"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A library for JOSE (JSON Object Signing and Encryption)"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "jose", "jwa", "jwe", "jwk", "jws", "jwt"]
homepage = "https://www.iota.org"

[dependencies]
anyhow = { version = "1.0", default-features = false }
base64 = { version = "0.12", default-features = false }
cfg-if = { version = "0.1", default-features = false }
paste = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
url = { version = "2.1", default-features = false, features = ["serde"] }

digest-crate = { version = "0.9", default-features = false, package = "digest" }
ed25519-dalek = { version = "1.0", default-features = false, features = ["u64_backend"] }
hmac-crate = { version = "0.9", default-features = false, package = "hmac" }
k256 = { version = "0.5", default-features = false, features = ["ecdsa-core", "ecdsa", "sha256", "zeroize"] }
p256 = { version = "0.5", default-features = false, features = ["ecdsa-core", "ecdsa", "sha256", "zeroize"] }
rand-crate = { version = "0.7", default-features = false, features = ["getrandom"], package = "rand" }
rsa-crate = { version = "0.3", default-features = false, package = "rsa" }
sha2 = { version = "0.9", default-features = false }
zeroize = { version = "1.1", default-features = false }

[features]
default = ["std"]

std = [
  "alloc",
  "anyhow/std",
  "base64/std",
  "serde/std",
  "serde_json/std",
]

alloc = [
  "base64/alloc",
  "serde/alloc",
  "serde_json/alloc",
]
